services:
  webhook:
    image: thecatlady/webhook
    container_name: webhook
    command: -verbose -hooks=hooks.json -hotreload
    environment:
      - TZ=Asia/Jakarta #optional
    volumes:
      - ./config:/config:ro
    ports:
      - 9000:9000
    restart: always