services:
  webhook:
    image: thecatlady/webhook
    container_name: webhook
    command: -verbose -hooks=hooks.json -hotreload
    environment:
      - TZ=Asia/Jakarta #optional
    volumes:
      - ./config:/config
      - /root/first:/opt/git
      - /root/second:/root/second
      - /root/third:/opt/third
    ports:
      - 9000:9000
    restart: always